stages: 
    - frontend-build
    - frontend-test
    
build:
    image: node:latest
    stage: frontend-build
    before_script:
        - cd frontend
        - yarn
    script:
        - yarn build

test:
    image: node:latest
    stage: frontend-test
    before_script:
        - cd frontend
        - yarn
    script:
        - yarn test
